name: assistant
description: assistant
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.3
  path_provider: ^2.1.1
  light: ^3.0.1
  torch_light: ^1.0.0
  intl: ^0.18.1
  lava_clock:
    path: ../lava_clock
  vosk_flutter: ^0.3.48
  picovoice_flutter: ^3.0.1
  porcupine_flutter: ^3.0.1
  cheetah_flutter: ^1.1.1
  volume_controller: ^2.0.7
  android_intent_plus: ^4.0.3
  json_annotation: ^4.8.1
  fluttertoast: ^8.2.4

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/sounds/
