name: assistant
description: assistant
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  takeout_lib:
    path: ../../takeout_app/takeout_lib/
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  hydrated_bloc: ^9.1.4
  path_provider: ^2.1.2
  light: ^3.0.1
  torch_light: ^1.0.0
  intl: ^0.18.1
  lava_clock:
    path: ../lava_clock
  vosk_flutter_2: ^1.0.5
  picovoice_flutter: ^3.0.3
  porcupine_flutter: ^3.0.3
  cheetah_flutter: ^1.1.1
  volume_controller: ^2.0.7
  android_intent_plus: ^4.0.3
  json_annotation: ^4.8.1
  fluttertoast: ^8.2.4
  wakelock_plus: ^1.1.4
  flutter_foreground_task: ^6.1.3
  flutter_svg: ^2.0.10+1
  one_clock: ^2.0.0
  flutter_hue: ^1.2.4
  colornames: ^0.1.0

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  test: ^1.24.9
  analyzer: ^6.4.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/images/
